In [22]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [23]:
df = pd.read_csv("Excels\\homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [24]:
X = df[['area']]
y = df['price']
reg = linear_model.LinearRegression().fit(X,y)

In [25]:
reg.coef_

array([135.78767123])

In [26]:
reg.intercept_

180616.43835616432

In [27]:
reg.predict([[5000]])

C:\Users\musta\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [28]:
import pickle 

with open("model_pickle",'wb') as f:  # wb = writing binary
    pickle.dump(reg,f)  
    # the file is saved now

In [29]:
with open("model_pickle","rb") as f:  # reading binary
    mp = pickle.load(f)

In [30]:
mp.predict([[5000]])

C:\Users\musta\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [31]:
#----Another Saving module-----#

In [37]:
import joblib # this is better when u use numpy array alot

In [38]:
joblib.dump(reg,"model_joblib")

['model_joblib']

In [40]:
mj = joblib.load("model_joblib")
mj.predict([[5000]])

C:\Users\musta\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])