In [34]:
# Data Preprocessing : Handling NA values
# Linear Regression Using Mutiple Variables

In [35]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [36]:
df = pd.read_csv("Excels\\homeprices2.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [37]:
median_bedrooms = df['bedrooms'].median()

In [38]:
df['bedrooms'].fillna(median_bedrooms,inplace=True)

In [39]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [40]:
X = df[['area','bedrooms','age']]
y = df['price']
reg = linear_model.LinearRegression().fit(X,y)

In [41]:
# Y = m1*area + m2*bedrooms + m3*age + b

In [42]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [43]:
reg.intercept_

221323.00186540408

In [44]:
reg.predict(X) # predicted prices of each dataset according to the independent variables (X)

array([518217.63297611, 602590.07937407, 615307.4140366 , 597962.89583192,
       760663.42675457, 795258.55102673])

In [45]:
reg.predict([[3000,3,40]]) # predictd price for 3000sqft 3 bedrooms 40 age

C:\Users\musta\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [46]:
#--------Hiring Excrise------#

In [47]:
df = pd.read_csv("Excels\\hiring.csv")
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [48]:
df['experience'] = df['experience'].fillna('zero')

In [49]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [50]:
df.isna().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [51]:
df[df['test_score(out of 10)'].isna()]

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
6        ten                    NaN                           7      72000

In [52]:
import math
test_mean = math.floor(df['test_score(out of 10)'].mean())
test_median = df['test_score(out of 10)'].median()
test_median

8.0

In [53]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(test_mean) 

In [54]:
df.isna().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [55]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [56]:
from word2number import w2n
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [57]:
X = df[['experience','test_score(out of 10)','interview_score(out of 10)']]
y = df['salary($)']
reg = linear_model.LinearRegression().fit(X,y)

In [58]:
reg.predict([[2,9,6]])

C:\Users\musta\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [59]:
reg.predict([[12,10,10]])

C:\Users\musta\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])